//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeOfArtifact
    {
        public int ID { get; set; }
        public int AttributeID { get; set; }
        public int ArtifactID { get; set; }
        public string Value { get; set; }
    
        public virtual Artifact Artifact { get; set; }
        public virtual Attribute Attribute { get; set; }
    }
}
